#pragma once

#include <cloudabi_types.h>

namespace cloudabi {

enum class error : cloudabi_errno_t {
	no_error       = 0,
	too_big        = CLOUDABI_E2BIG,
	acces          = CLOUDABI_EACCES,
	addrinuse      = CLOUDABI_EADDRINUSE,
	addrnotavail   = CLOUDABI_EADDRNOTAVAIL,
	afnosupport    = CLOUDABI_EAFNOSUPPORT,
	again          = CLOUDABI_EAGAIN,
	already        = CLOUDABI_EALREADY,
	badf           = CLOUDABI_EBADF,
	badmsg         = CLOUDABI_EBADMSG,
	busy           = CLOUDABI_EBUSY,
	canceled       = CLOUDABI_ECANCELED,
	child          = CLOUDABI_ECHILD,
	connaborted    = CLOUDABI_ECONNABORTED,
	connrefused    = CLOUDABI_ECONNREFUSED,
	connreset      = CLOUDABI_ECONNRESET,
	deadlk         = CLOUDABI_EDEADLK,
	destaddrreq    = CLOUDABI_EDESTADDRREQ,
	dom            = CLOUDABI_EDOM,
	dquot          = CLOUDABI_EDQUOT,
	exist          = CLOUDABI_EEXIST,
	fault          = CLOUDABI_EFAULT,
	fbig           = CLOUDABI_EFBIG,
	hostunreach    = CLOUDABI_EHOSTUNREACH,
	idrm           = CLOUDABI_EIDRM,
	ilseq          = CLOUDABI_EILSEQ,
	inprogress     = CLOUDABI_EINPROGRESS,
	intr           = CLOUDABI_EINTR,
	inval          = CLOUDABI_EINVAL,
	io             = CLOUDABI_EIO,
	isconn         = CLOUDABI_EISCONN,
	isdir          = CLOUDABI_EISDIR,
	loop           = CLOUDABI_ELOOP,
	mfile          = CLOUDABI_EMFILE,
	mlink          = CLOUDABI_EMLINK,
	msgsize        = CLOUDABI_EMSGSIZE,
	multihop       = CLOUDABI_EMULTIHOP,
	nametoolong    = CLOUDABI_ENAMETOOLONG,
	netdown        = CLOUDABI_ENETDOWN,
	netreset       = CLOUDABI_ENETRESET,
	netunreach     = CLOUDABI_ENETUNREACH,
	nfile          = CLOUDABI_ENFILE,
	nobufs         = CLOUDABI_ENOBUFS,
	nodev          = CLOUDABI_ENODEV,
	noent          = CLOUDABI_ENOENT,
	noexec         = CLOUDABI_ENOEXEC,
	nolck          = CLOUDABI_ENOLCK,
	nolink         = CLOUDABI_ENOLINK,
	nomem          = CLOUDABI_ENOMEM,
	nomsg          = CLOUDABI_ENOMSG,
	noprotoopt     = CLOUDABI_ENOPROTOOPT,
	nospc          = CLOUDABI_ENOSPC,
	nosys          = CLOUDABI_ENOSYS,
	notconn        = CLOUDABI_ENOTCONN,
	notdir         = CLOUDABI_ENOTDIR,
	notempty       = CLOUDABI_ENOTEMPTY,
	notrecoverable = CLOUDABI_ENOTRECOVERABLE,
	notsock        = CLOUDABI_ENOTSOCK,
	notsup         = CLOUDABI_ENOTSUP,
	notty          = CLOUDABI_ENOTTY,
	nxio           = CLOUDABI_ENXIO,
	overflow       = CLOUDABI_EOVERFLOW,
	ownerdead      = CLOUDABI_EOWNERDEAD,
	perm           = CLOUDABI_EPERM,
	pipe           = CLOUDABI_EPIPE,
	proto          = CLOUDABI_EPROTO,
	protonosupport = CLOUDABI_EPROTONOSUPPORT,
	prototype      = CLOUDABI_EPROTOTYPE,
	range          = CLOUDABI_ERANGE,
	rofs           = CLOUDABI_EROFS,
	spipe          = CLOUDABI_ESPIPE,
	srch           = CLOUDABI_ESRCH,
	stale          = CLOUDABI_ESTALE,
	timedout       = CLOUDABI_ETIMEDOUT,
	txtbsy         = CLOUDABI_ETXTBSY,
	xdev           = CLOUDABI_EXDEV,
	notcapable     = CLOUDABI_ENOTCAPABLE,
};

}
